//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBanco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public int id { get; set; }
        public Nullable<int> anoFabricacao { get; set; }
        public Nullable<int> anoModelo { get; set; }
        public string cor { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
    }
}
