//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBanco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prova
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> nota1 { get; set; }
        public Nullable<decimal> nota2 { get; set; }
        public Nullable<decimal> media { get; set; }
    }
}
